# -*- coding: utf-8 -*-
"""train_model.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1h-rU2ghMK-pmrLR-cH3vyZbqeCXFw5iQ
"""

# train_model.py
import numpy as np
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv2D, MaxPooling2D, Flatten, Dense, Dropout
from tensorflow.keras.utils import to_categorical
from tensorflow.keras.optimizers import Adam

# Simulate dummy training data (500 fake face-like images)
num_classes = 5
X_train = np.random.rand(500, 224, 224, 3)
y_train = to_categorical(np.random.randint(0, num_classes, 500), num_classes)

# Build the CNN
model = Sequential([
    Conv2D(32, (3,3), activation='relu', input_shape=(224,224,3)),
    MaxPooling2D((2,2)),
    Conv2D(64, (3,3), activation='relu'),
    MaxPooling2D((2,2)),
    Flatten(),
    Dense(128, activation='relu'),
    Dropout(0.5),
    Dense(num_classes, activation='softmax')
])

model.compile(optimizer=Adam(), loss='categorical_crossentropy', metrics=['accuracy'])

# Train
model.fit(X_train, y_train, epochs=3, batch_size=32)

# Save the model
model.save("models/nutrient_model.h5")
print("✅ Model saved successfully.")